---
- name: Clone multiple VMs
  hosts: localhost 
  gather_facts: false
  vars_files: 
    variables.yml
  tasks: 
  - name: Clone multiple VMs from template
    local_action:
      module: vmware_guest
      hostname: "{{ vcenter_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no      
      folder: "{{ folder }}"
      template: "{{ vmtemplate }}"
      name: "{{ item }}"
      cluster: "{{ vmcluster }}"
      datacenter: NSXT
      state: poweredon
 loop: "{{ servers }}"
    async: 60
    poll: 0
