---
- name: Get current target host's IP address using shell command
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    variables.yml

  tasks:
    - name: Fetch IP address using shell command
      vars:
        command: " {{ item }} -I | awk '{print $1}'"
      shell: "{{ command }}"
      register: ip_address_result

    - name: Display the IP address
      debug:
        var: ip_address_result.stdout

      loop: "{{ servers }}"   
